name: request_hub_create_casefile
display_name: RequestHub • Create Casefile
description: Create a casefile through RequestHub with hook execution and policy defaults.
category: workspace
version: "0.1.0"
tags:
  - request-hub
  - casefile
  - hooks

metadata:
  source_method: execute_casefile
  service: RequestHubService
  generated_from: methods_inventory_v1.yaml
  policy_pattern: default

classification:
  domain: workspace
  subdomain: casefile
  capability: create
  complexity: atomic
  maturity: experimental
  integration_tier: internal

parameters:
  - name: title
    type: string
    required: true
    description: Primary title for the casefile.
    example: "AI Request Hub Demo"
  - name: description
    type: string
    required: false
    description: Optional descriptive text for the casefile.
    default: ""
  - name: tags
    type: array
    items: string
    required: false
    description: Labels applied to the new casefile.
    default: []
  - name: hook_channels
    type: array
    items: string
    required: false
    description: Additional hook identifiers to activate.
    default:
      - metrics
      - audit

implementation:
  type: api_call
  api_call:
    method_name: execute_casefile
    service: RequestHubService
    request_mapping:
      operation: "create_casefile"
      request_id: "{{ request_id }}"
      session_id: "{{ session.session_id }}"
      user_id: "{{ session.user_id }}"
      context_requirements:
        - session
      hooks: "{{ hook_channels }}"
      policy_hints:
        pattern: "default"
      metadata:
        parent_tool: "request_hub_create_casefile"
      payload:
        title: "{{ title }}"
        description: "{{ description }}"
        tags: "{{ tags }}"

returns:
  type: object
  description: Newly created casefile details with hook metadata.
  properties:
    casefile_id:
      type: string
      description: Identifier of the created casefile.
    status:
      type: string
      description: Execution status from RequestHub response.
    hooks_executed:
      type: array
      items: string
      description: Hook identifiers executed during the workflow.
    metadata:
      type: object
      description: Response metadata including hook/audit logs when available.
  required:
    - casefile_id
    - status

session_policies:
  requires_active_session: true
  allow_new_session: false
  allow_session_resume: true
  session_event_type: request
  log_request_payload: true
  log_full_response: true

audit_events:
  success_event: request_hub_casefile_created
  failure_event: request_hub_casefile_failed
  log_response_fields:
    - casefile_id
    - status
  emit_casefile_event: true

documentation:
  summary: |
    Executes the RequestHub casefile creation workflow with configurable hook channels
    and policy defaults. Ideal for testing RequestHub orchestration end-to-end.
  usage: |
    Provide a title and optionally description/tags. Hooks default to metrics and audit
    but can be extended per invocation.

test_scenarios:
  happy_paths:
    - name: create_basic_casefile
      description: Create a casefile with minimal inputs through RequestHub.
      environment: valid_user_session
      input:
        title: "RequestHub Casefile"
      expected:
        status: "COMPLETED"
        hooks_executed: ["metrics", "audit"]
  unhappy_paths:
    - name: missing_title
      description: Expect validation error when title is missing.
      environment: valid_user_session
      input: {}
      expected_error:
        type: ValidationError
        message_contains: "title"

