services:
  solid-server:
    image: solidproject/community-server:latest
    container_name: tiny-collider-solid
    ports:
      - "3000:3000"
    volumes:
      - ./solid-data:/data
      - ./solid-config:/config
    environment:
      - CSS_CONFIG=/config/config.json
      - CSS_BASE_URL=http://localhost:3000/
      - CSS_PORT=3000
      - CSS_LOGGING_LEVEL=info
    restart: unless-stopped
    command: npx @solid/community-server -c /config/config.json -p 3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Optional: Your Tiny Data Collider API
  # Uncomment when you want to run both together
  # collider-api:
  #   build: .
  #   container_name: tiny-collider-api
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - solid-server
  #   environment:
  #     - SOLID_ENABLED=true
  #     - SOLID_POD_URL=http://solid-server:3000/
  #     - ENVIRONMENT=development
  #   volumes:
  #     - .:/app
  #     - ./solid-data:/solid-data:ro
  #   restart: unless-stopped

networks:
  default:
    name: tiny-collider-network
