name: gmail_list_messages
display_name: Gmail List Messages
description: "List Gmail messages for the authenticated user with optional filtering"
version: "1.0.0"
category: google_workspace
tags:
  - gmail
  - email
  - google_workspace
  - communication

parameters:
  - name: max_results
    type: integer
    description: "Maximum number of messages to return"
    required: false
    default: 10
    min_value: 1
    max_value: 100
    
  - name: query
    type: string
    description: "Gmail search query string (e.g. 'is:unread', 'from:example@gmail.com')"
    required: false
    default: ""
    
  - name: label_ids
    type: array
    description: "List of label IDs to filter by (e.g. ['INBOX', 'UNREAD'])"
    required: false
    default: []

business_rules:
  enabled: true
  requires_auth: true
  required_permissions: ["gmail.readonly"]
  requires_casefile: false
  timeout_seconds: 30

session_policies:
  requires_active_session: true
  allow_new_session: false
  allow_session_resume: true
  session_event_type: "gmail_list"
  log_request_payload: true
  log_full_response: false

casefile_policies:
  requires_casefile: false
  allowed_casefile_states: ["active"]
  create_if_missing: false
  enforce_access_control: true
  audit_casefile_changes: false

implementation:
  type: api_call
  api_call:
    client_module: "src.pydantic_ai_integration.integrations.google_workspace.clients"
    client_class: "GmailClient"
    method_name: "list_messages"
    response_type: "GmailListMessagesResponse"

returns:
  type: object
  description: "Gmail messages list response"
  properties:
    messages:
      type: array
      description: "List of Gmail message objects"
    result_size_estimate:
      type: integer
      description: "Estimated total number of results"
    next_page_token:
      type: string
      description: "Token for pagination"

audit_events:
  success_event: "gmail_list_success"
  failure_event: "gmail_list_failure"
  log_response_fields: ["result_size_estimate"]
  redact_fields: []
  emit_casefile_event: true

examples:
  - description: "List recent inbox messages"
    context:
      session:
        user_id: "test_user"
        session_id: "test_session"
    input:
      max_results: 5
      label_ids: ["INBOX"]
    expected_output:
      messages:
        - id: "mock-msg-1"
          subject: "Mock subject"
      result_size_estimate: 2

error_scenarios:
  - description: "Invalid max_results"
    input:
      max_results: 200
    expected_error:
      type: "ValidationError"
      message: "max_results must be between 1 and 100"

test_scenarios:
  - name: "unread_messages"
    description: "List unread messages only"
    parameters:
      max_results: 10
      query: "is:unread"
    expected_output:
      result_size_estimate: 2
