name: gmail_search_messages
display_name: Gmail Search Messages
description: "Search Gmail messages using advanced query syntax"
version: "1.0.0"
category: google_workspace
tags:
  - gmail
  - email
  - google_workspace
  - search

parameters:
  - name: query
    type: string
    description: "Gmail search query (e.g. 'from:user@example.com after:2024/01/01')"
    required: true
    min_length: 1
    
  - name: max_results
    type: integer
    description: "Maximum number of results to return"
    required: false
    default: 20
    min_value: 1
    max_value: 100
    
  - name: include_spam_trash
    type: boolean
    description: "Include messages from SPAM and TRASH"
    required: false
    default: false

business_rules:
  enabled: true
  requires_auth: true
  required_permissions: ["gmail.readonly"]
  requires_casefile: false
  timeout_seconds: 30

session_policies:
  requires_active_session: true
  allow_new_session: false
  allow_session_resume: true
  session_event_type: "gmail_search"
  log_request_payload: true
  log_full_response: false

casefile_policies:
  requires_casefile: false
  allowed_casefile_states: ["active"]
  create_if_missing: false
  enforce_access_control: true
  audit_casefile_changes: false

implementation:
  type: api_call
  api_call:
    client_module: "src.pydantic_ai_integration.integrations.google_workspace.clients"
    client_class: "GmailClient"
    method_name: "search_messages"
    response_type: "GmailSearchMessagesResponse"

returns:
  type: object
  description: "Search results with messages"
  properties:
    messages:
      type: array
      description: "List of matching Gmail messages"
    result_size_estimate:
      type: integer
      description: "Estimated number of matching messages"
    query_used:
      type: string
      description: "The search query that was executed"

audit_events:
  success_event: "gmail_search_success"
  failure_event: "gmail_search_failure"
  log_response_fields: ["result_size_estimate", "query_used"]
  redact_fields: []
  emit_casefile_event: true

examples:
  - description: "Search for unread messages from specific sender"
    context:
      session:
        user_id: "test_user"
        session_id: "test_session"
    input:
      query: "from:notifications@example.com is:unread"
      max_results: 10
    expected_output:
      messages:
        - id: "mock-msg-1"
          subject: "Notification"
      result_size_estimate: 5
      query_used: "from:notifications@example.com is:unread"

error_scenarios:
  - description: "Empty query string"
    input:
      query: ""
    expected_error:
      type: "ValidationError"
      message: "query must be at least 1 character"

test_scenarios:
  - name: "search_by_date_range"
    description: "Search messages within date range"
    parameters:
      query: "after:2024/01/01 before:2024/12/31"
      max_results: 50
    expected_output:
      result_size_estimate: 10
