# Gmail to Drive Pipeline - Composite Tool Example
#
# Demonstrates tool composition by chaining:
# 1. Search Gmail for messages matching criteria
# 2. Extract attachments from found messages
# 3. Upload attachments to Google Drive
# 4. Record results in casefile

name: gmail_to_drive_pipeline
display_name: Gmail to Drive Pipeline
description: Search Gmail messages and upload attachments to Google Drive
category: google_workspace
version: 1.0.0
tags:
  - gmail
  - drive
  - composite
  - pipeline

business_rules:
  enabled: true
  requires_auth: true
  required_permissions:
    - gmail.read
    - drive.write
  timeout_seconds: 120
  requires_casefile: true

session_policies:
  requires_active_session: true
  allow_new_session: false
  session_event_type: request

casefile_policies:
  requires_casefile: true
  allowed_casefile_states:
    - active
  enforce_access_control: true
  audit_casefile_changes: true

parameters:
  - name: gmail_query
    type: string
    description: Gmail search query (e.g., 'from:example@gmail.com has:attachment')
    required: true
    min_length: 1
    examples:
      - 'has:attachment after:2025/01/01'
      - 'from:client@example.com subject:invoice'

  - name: max_messages
    type: integer
    description: Maximum number of messages to process
    required: false
    default: 10
    min_value: 1
    max_value: 100

  - name: drive_folder_id
    type: string
    description: Google Drive folder ID to upload attachments to
    required: true
    min_length: 1
    examples:
      - '1abc_XYZ-folder-id-123'

implementation:
  type: composite
  composite:
    steps:
      # Step 1: Search Gmail for matching messages
      - tool: gmail_search_messages
        inputs:
          query: '{{ state.gmail_query }}'
          max_results: '{{ state.max_messages }}'
        on_success:
          next: process_messages
          map_outputs:
            messages: search_results
        on_failure:
          action: stop

      # Step 2: Process found messages (placeholder for future message processor)
      # For now, we'll just extract the first message
      - tool: gmail_get_message
        inputs:
          message_id: '{{ state.search_results[0].id }}'
        on_success:
          map_outputs:
            message: current_message
          next: upload_to_drive
        on_failure:
          action: continue
          next: record_results

      # Step 3: Upload to Drive (simplified - real version would extract attachments)
      - tool: drive_upload_file
        inputs:
          name: 'gmail_export_{{ state.chain_id }}.json'
          parent_folder_id: '{{ state.drive_folder_id }}'
          mime_type: 'application/json'
          content: '{{ state.current_message }}'
        on_success:
          map_outputs:
            file: uploaded_file
        on_failure:
          action: retry
          max_retries: 3

returns:
  type: object
  description: Pipeline execution results
  properties:
    success:
      type: boolean
    chain_id:
      type: string
    messages_found:
      type: integer
    messages_processed:
      type: integer
    files_uploaded:
      type: integer
    drive_files:
      type: array
    execution_history:
      type: array

audit_events:
  success_event: gmail_to_drive_pipeline.success
  failure_event: gmail_to_drive_pipeline.failure
  log_response_fields:
    - messages_found
    - files_uploaded
  emit_casefile_event: true

examples:
  - description: Export invoices from Gmail to Drive
    context:
      session:
        user_id: user_abc123
        session_id: session_xyz789
        casefile_id: casefile_invoice_export
    input:
      gmail_query: 'from:vendor@example.com subject:invoice has:attachment'
      max_messages: 20
      drive_folder_id: '1abc_invoices_folder'
    expected_output:
      success: true
      messages_found: 15
      messages_processed: 15
      files_uploaded: 23
    expect_casefile_changes: true

  - description: Backup important emails with attachments
    context:
      session:
        user_id: user_def456
        session_id: session_uvw123
        casefile_id: casefile_email_backup
    input:
      gmail_query: 'is:important has:attachment after:2025/01/01'
      max_messages: 50
      drive_folder_id: '1xyz_backup_folder'
    expected_output:
      success: true
      messages_found: 42
      messages_processed: 42
      files_uploaded: 87
    expect_casefile_changes: true

documentation:
  summary: |
    Composite tool demonstrating tool chaining for Gmail to Drive workflows.
    Searches Gmail messages, extracts data/attachments, and uploads to Drive.
    
    Use Cases:
    - Invoice/receipt archival
    - Email backup workflows
    - Document extraction pipelines
    - Automated filing systems
    
    Prerequisites:
    - Active session with Gmail and Drive permissions
    - Valid Drive folder ID
    - Casefile for tracking pipeline executions
