create_casefile:
  name: create_casefile
  description: Create new casefile with metadata
  version: 1.0.0
  classification:
    domain: workspace
    subdomain: casefile
    capability: create
    complexity: atomic
    maturity: stable
    integration_tier: internal
  models:
    request: CreateCasefileRequest
    response: CreateCasefileResponse
  implementation:
    class: CasefileService
    method: create_casefile
get_casefile:
  name: get_casefile
  description: Retrieve casefile by ID
  version: 1.0.0
  classification:
    domain: workspace
    subdomain: casefile
    capability: read
    complexity: atomic
    maturity: stable
    integration_tier: internal
  models:
    request: GetCasefileRequest
    response: GetCasefileResponse
  implementation:
    class: CasefileService
    method: get_casefile
update_casefile:
  name: update_casefile
  description: Update casefile metadata
  version: 1.0.0
  classification:
    domain: workspace
    subdomain: casefile
    capability: update
    complexity: atomic
    maturity: stable
    integration_tier: internal
  models:
    request: UpdateCasefileRequest
    response: UpdateCasefileResponse
  implementation:
    class: CasefileService
    method: update_casefile
list_casefiles:
  name: list_casefiles
  description: List casefiles with optional filters
  version: 1.0.0
  classification:
    domain: workspace
    subdomain: casefile
    capability: search
    complexity: atomic
    maturity: stable
    integration_tier: internal
  models:
    request: ListCasefilesRequest
    response: ListCasefilesResponse
  implementation:
    class: CasefileService
    method: list_casefiles
delete_casefile:
  name: delete_casefile
  description: Delete casefile permanently
  version: 1.0.0
  classification:
    domain: workspace
    subdomain: casefile
    capability: delete
    complexity: atomic
    maturity: stable
    integration_tier: internal
  models:
    request: DeleteCasefileRequest
    response: DeleteCasefileResponse
  implementation:
    class: CasefileService
    method: delete_casefile
add_session_to_casefile:
  name: add_session_to_casefile
  description: Link tool/chat session to casefile
  version: 1.0.0
  classification:
    domain: workspace
    subdomain: casefile
    capability: update
    complexity: atomic
    maturity: stable
    integration_tier: internal
  models:
    request: AddSessionToCasefileRequest
    response: AddSessionToCasefileResponse
  implementation:
    class: CasefileService
    method: add_session_to_casefile
store_gmail_messages:
  name: store_gmail_messages
  description: Store Gmail messages in casefile
  version: 1.0.0
  classification:
    domain: workspace
    subdomain: google_workspace
    capability: update
    complexity: composite
    maturity: beta
    integration_tier: hybrid
  models:
    request: StoreGmailMessagesRequest
    response: StoreGmailMessagesResponse
  implementation:
    class: CasefileService
    method: store_gmail_messages
store_drive_files:
  name: store_drive_files
  description: Store Google Drive files in casefile
  version: 1.0.0
  classification:
    domain: workspace
    subdomain: google_workspace
    capability: update
    complexity: composite
    maturity: beta
    integration_tier: hybrid
  models:
    request: StoreDriveFilesRequest
    response: StoreDriveFilesResponse
  implementation:
    class: CasefileService
    method: store_drive_files
store_sheet_data:
  name: store_sheet_data
  description: Store Google Sheets data in casefile
  version: 1.0.0
  classification:
    domain: workspace
    subdomain: google_workspace
    capability: update
    complexity: composite
    maturity: beta
    integration_tier: hybrid
  models:
    request: StoreSheetDataRequest
    response: StoreSheetDataResponse
  implementation:
    class: CasefileService
    method: store_sheet_data
grant_permission:
  name: grant_permission
  description: Grant user permission on casefile
  version: 1.0.0
  classification:
    domain: workspace
    subdomain: casefile_acl
    capability: update
    complexity: atomic
    maturity: stable
    integration_tier: internal
  models:
    request: GrantPermissionRequest
    response: GrantPermissionResponse
  implementation:
    class: CasefileService
    method: grant_permission
revoke_permission:
  name: revoke_permission
  description: Revoke user permission on casefile
  version: 1.0.0
  classification:
    domain: workspace
    subdomain: casefile_acl
    capability: delete
    complexity: atomic
    maturity: stable
    integration_tier: internal
  models:
    request: RevokePermissionRequest
    response: RevokePermissionResponse
  implementation:
    class: CasefileService
    method: revoke_permission
list_permissions:
  name: list_permissions
  description: List all permissions for casefile
  version: 1.0.0
  classification:
    domain: workspace
    subdomain: casefile_acl
    capability: read
    complexity: atomic
    maturity: stable
    integration_tier: internal
  models:
    request: ListPermissionsRequest
    response: ListPermissionsResponse
  implementation:
    class: CasefileService
    method: list_permissions
check_permission:
  name: check_permission
  description: Check if user has specific permission
  version: 1.0.0
  classification:
    domain: workspace
    subdomain: casefile_acl
    capability: read
    complexity: atomic
    maturity: stable
    integration_tier: internal
  models:
    request: CheckPermissionRequest
    response: CheckPermissionResponse
  implementation:
    class: CasefileService
    method: check_permission
create_session:
  name: create_session
  description: Create chat session (tool session created lazily)
  version: 1.0.0
  classification:
    domain: communication
    subdomain: chat_session
    capability: create
    complexity: atomic
    maturity: stable
    integration_tier: internal
  models:
    request: CreateChatSessionRequest
    response: CreateChatSessionResponse
  implementation:
    class: CommunicationService
    method: create_session
get_session:
  name: get_session
  description: Retrieve chat session by ID
  version: 1.0.0
  classification:
    domain: communication
    subdomain: chat_session
    capability: read
    complexity: atomic
    maturity: stable
    integration_tier: internal
  models:
    request: GetChatSessionRequest
    response: GetChatSessionResponse
  implementation:
    class: CommunicationService
    method: get_session
list_sessions:
  name: list_sessions
  description: List chat sessions with filters
  version: 1.0.0
  classification:
    domain: communication
    subdomain: chat_session
    capability: search
    complexity: atomic
    maturity: stable
    integration_tier: internal
  models:
    request: ListChatSessionsRequest
    response: ListChatSessionsResponse
  implementation:
    class: CommunicationService
    method: list_sessions
close_session:
  name: close_session
  description: Close chat session
  version: 1.0.0
  classification:
    domain: communication
    subdomain: chat_session
    capability: update
    complexity: atomic
    maturity: stable
    integration_tier: internal
  models:
    request: CloseChatSessionRequest
    response: CloseChatSessionResponse
  implementation:
    class: CommunicationService
    method: close_session
process_tool_request_with_session_management:
  name: process_tool_request_with_session_management
  description: Process tool request with automatic session management
  version: 1.0.0
  classification:
    domain: automation
    subdomain: tool_execution
    capability: process
    complexity: composite
    maturity: stable
    integration_tier: hybrid
  models:
    request: 'null'
    response: ToolResponse
  implementation:
    class: ToolSessionService
    method: process_tool_request_with_session_management
process_chat_request:
  name: process_chat_request
  description: Parse message, call LLM, handle tool calls
  version: 1.0.0
  classification:
    domain: communication
    subdomain: chat_processing
    capability: process
    complexity: pipeline
    maturity: stable
    integration_tier: hybrid
  models:
    request: ChatRequest
    response: ChatResponse
  implementation:
    class: CommunicationService
    method: process_chat_request
execute_casefile:
  name: execute_casefile
  description: Create casefile through RequestHub with hook support
  version: 1.0.0
  classification:
    domain: workspace
    subdomain: casefile
    capability: create
    complexity: atomic
    maturity: beta
    integration_tier: internal
  models:
    request: 'null'
    response: 'null'
  implementation:
    class: RequestHubService
    method: execute_casefile
execute_casefile_with_session:
  name: execute_casefile_with_session
  description: Composite workflow creating a casefile and tool session
  version: 1.0.0
  classification:
    domain: workspace
    subdomain: casefile
    capability: create
    complexity: composite
    maturity: beta
    integration_tier: internal
  models:
    request: 'null'
    response: 'null'
  implementation:
    class: RequestHubService
    method: execute_casefile_with_session
create_session_with_casefile:
  name: create_session_with_casefile
  description: Create tool session and link to existing casefile
  version: 1.0.0
  classification:
    domain: automation
    subdomain: tool_session
    capability: create
    complexity: composite
    maturity: beta
    integration_tier: internal
  models:
    request: 'null'
    response: 'null'
  implementation:
    class: RequestHubService
    method: create_session_with_casefile
list_messages:
  name: list_messages
  description: List Gmail messages
  version: 1.0.0
  classification:
    domain: communication
    subdomain: gmail
    capability: read
    complexity: atomic
    maturity: beta
    integration_tier: external
  models:
    request: 'null'
    response: 'null'
  implementation:
    class: GmailClient
    method: list_messages
send_message:
  name: send_message
  description: Send Gmail message
  version: 1.0.0
  classification:
    domain: communication
    subdomain: gmail
    capability: create
    complexity: atomic
    maturity: beta
    integration_tier: external
  models:
    request: 'null'
    response: 'null'
  implementation:
    class: GmailClient
    method: send_message
search_messages:
  name: search_messages
  description: Search Gmail messages by query
  version: 1.0.0
  classification:
    domain: communication
    subdomain: gmail
    capability: search
    complexity: atomic
    maturity: beta
    integration_tier: external
  models:
    request: 'null'
    response: 'null'
  implementation:
    class: GmailClient
    method: search_messages
get_message:
  name: get_message
  description: Get single Gmail message by ID
  version: 1.0.0
  classification:
    domain: communication
    subdomain: gmail
    capability: read
    complexity: atomic
    maturity: beta
    integration_tier: external
  models:
    request: 'null'
    response: 'null'
  implementation:
    class: GmailClient
    method: get_message
list_files:
  name: list_files
  description: List Google Drive files
  version: 1.0.0
  classification:
    domain: workspace
    subdomain: google_drive
    capability: read
    complexity: atomic
    maturity: beta
    integration_tier: external
  models:
    request: 'null'
    response: 'null'
  implementation:
    class: DriveClient
    method: list_files
batch_get:
  name: batch_get
  description: Batch get Google Sheets data
  version: 1.0.0
  classification:
    domain: workspace
    subdomain: google_sheets
    capability: read
    complexity: atomic
    maturity: beta
    integration_tier: external
  models:
    request: 'null'
    response: 'null'
  implementation:
    class: SheetsClient
    method: batch_get
