# Gmail List Messages Tool Definition
# This tool lists messages from Gmail inbox with optional filtering

name: gmail_list_messages
display_name: "List Gmail Messages"
description: "List messages from Gmail inbox with optional query filtering"
category: google_workspace
version: "1.0.0"
tags:
  - gmail
  - messages
  - list
  - google

# Business rules
requires_auth: true
required_permissions:
  - gmail:read
requires_casefile: true
timeout_seconds: 30
enabled: true

# Parameters
parameters:
  - name: max_results
    type: integer
    required: false
    default: 10
    min_value: 1
    max_value: 100
    description: "Maximum number of messages to return"
  
  - name: query
    type: string
    required: false
    default: ""
    max_length: 500
    description: "Gmail search query (e.g., 'from:sender@example.com')"
  
  - name: label_ids
    type: array
    required: false
    default: null
    description: "List of label IDs to filter by"
  
  - name: include_spam_trash
    type: boolean
    required: false
    default: false
    description: "Whether to include spam and trash messages"

# Implementation details
stores_in_casefile: true
casefile_resource_type: gmail_messages

# Expected response structure
response_schema:
  messages:
    type: array
    description: "List of message objects with id and threadId"
  result_size_estimate:
    type: integer
    description: "Estimated total number of matching messages"
  message_count:
    type: integer
    description: "Actual number of messages returned"
  next_page_token:
    type: string
    description: "Token for retrieving next page of results"
