# Gmail Get Message Tool Definition
# This tool retrieves a specific Gmail message by ID

name: gmail_get_message
display_name: "Get Gmail Message"
description: "Retrieve a specific Gmail message by ID with full details"
category: google_workspace
version: "1.0.0"
tags:
  - gmail
  - message
  - get
  - google

# Business rules
requires_auth: true
required_permissions:
  - gmail:read
requires_casefile: true
timeout_seconds: 30
enabled: true

# Parameters
parameters:
  - name: message_id
    type: string
    required: true
    min_length: 1
    max_length: 100
    description: "The ID of the message to retrieve"
  
  - name: format
    type: string
    required: false
    default: "full"
    enum_values:
      - full
      - metadata
      - minimal
      - raw
    description: "The format to return the message in"
  
  - name: metadata_headers
    type: array
    required: false
    default: null
    description: "List of headers to return (when format='metadata')"

# Implementation details
stores_in_casefile: true
casefile_resource_type: gmail_message_detail

# Expected response structure
response_schema:
  id:
    type: string
    description: "Message ID"
  thread_id:
    type: string
    description: "Thread ID"
  label_ids:
    type: array
    description: "List of label IDs applied to the message"
  snippet:
    type: string
    description: "Short preview of the message"
  headers:
    type: array
    description: "Message headers (Subject, From, To, Date, etc.)"
  mime_type:
    type: string
    description: "MIME type of the message"
  body:
    type: object
    description: "Message body content"
