name: update_casefile_tool
description: Tool wrapper for CasefileService.update_casefile with validation and execution control
category: workspace_management
version: 1.0.0
tags:
- workspace
- casefile
- update
method_reference:
  service: CasefileService
  method: update_casefile
  classification:
    domain: workspace
    subdomain: casefile
    capability: update
    complexity: atomic
    maturity: stable
    integration_tier: internal
method_params:
- name: casefile_id
  type: string
  required: true
  description: Casefile ID to update
- name: title
  type: string
  required: false
  description: New title
- name: description
  type: string
  required: false
  description: New description
- name: tags
  type: string
  required: false
  description: New tags (replaces existing)
- name: notes
  type: string
  required: false
  description: New notes
tool_params:
- name: casefile_id
  type: string
  required: true
  description: Casefile ID to update
- name: title
  type: string
  required: false
  description: New title
- name: description
  type: string
  required: false
  description: New description
- name: tags
  type: string
  required: false
  description: New tags (replaces existing)
- name: notes
  type: string
  required: false
  description: New notes
- name: timeout_seconds
  type: integer
  required: false
  description: Maximum execution time in seconds
  default: 30
  min_value: 5
  max_value: 300
- name: dry_run
  type: boolean
  required: false
  description: Preview mode without actual execution
  default: false
implementation:
  type: method_wrapper
  method_wrapper:
    method_name: CasefileService.update_casefile
    parameter_mapping:
      method_params:
      - casefile_id
      - title
      - description
      - tags
      - notes
      tool_params:
      - timeout_seconds
      - dry_run
business_rules:
  enabled: true
  requires_auth: true
  required_permissions:
  - casefiles:write
  requires_casefile: true
  timeout_seconds: 30
examples:
- description: Basic update_casefile operation
  input:
    casefile_id: sample_casefile_id
    title: sample_title
  expected_output:
    result: success
    data: {}
data_contracts:
  request_model: UpdateCasefileRequest
  response_model: UpdateCasefileResponse
  canonical_models: []
  module: src.pydantic_models.operations.casefile_ops
dependencies:
  methods:
  - update_casefile
  models:
  - UpdateCasefileRequest
  - UpdateCasefileResponse
  services:
  - CasefileService
compatibility:
  method_version: 1.0.0
  schema_version: '1.0'
  requires_auth: true
