name: grant_permission_tool
description: Tool wrapper for casefile.grant_permission with validation and execution control
category: workspace_management
version: 1.0.0
tags:
- workspace
- casefile_acl
- update
method_reference:
  service: casefile
  method: grant_permission
  classification:
    domain: workspace
    subdomain: casefile_acl
    capability: update
    complexity: atomic
    maturity: stable
    integration_tier: internal
method_params:
- name: casefile_id
  type: string
  required: true
  description: Casefile ID
- name: target_user_id
  type: string
  required: true
  description: User to grant permission to
- name: permission
  type: string
  required: true
  description: Permission level to grant
- name: expires_at
  type: string
  required: false
  description: Optional expiration timestamp
- name: notes
  type: string
  required: false
  description: Optional notes
tool_params:
- name: casefile_id
  type: string
  required: true
  description: Casefile ID
- name: target_user_id
  type: string
  required: true
  description: User to grant permission to
- name: permission
  type: string
  required: true
  description: Permission level to grant
- name: expires_at
  type: string
  required: false
  description: Optional expiration timestamp
- name: notes
  type: string
  required: false
  description: Optional notes
- name: timeout_seconds
  type: integer
  required: false
  description: Maximum execution time in seconds
  default: 30
  min_value: 5
  max_value: 300
- name: dry_run
  type: boolean
  required: false
  description: Preview mode without actual execution
  default: false
implementation:
  type: method_wrapper
  method_wrapper:
    method_name: casefile.grant_permission
    parameter_mapping:
      method_params:
      - casefile_id
      - target_user_id
      - permission
      - expires_at
      - notes
      tool_params:
      - timeout_seconds
      - dry_run
business_rules:
  enabled: true
  requires_auth: true
  required_permissions: []
  requires_casefile: false
  timeout_seconds: 30
examples:
- description: Basic grant_permission operation
  input:
    casefile_id: sample_casefile_id
    target_user_id: sample_target_user_id
  expected_output:
    result: success
    data: {}
data_contracts:
  request_model: GrantPermissionRequest
  response_model: GrantPermissionResponse
  canonical_models: []
  module: pydantic_models.operations.casefile_ops
dependencies:
  methods:
  - grant_permission
  models:
  - GrantPermissionRequest
  - GrantPermissionResponse
  services:
  - casefile
compatibility:
  method_version: 1.0.0
  schema_version: '1.0'
  requires_auth: true
