name: grant_permission_tool
description: Tool wrapper for CasefileService.grant_permission with validation and
  execution control
category: workspace_management
version: 1.0.0
tags:
- workspace
- update
- grant
method_reference:
  service: CasefileService
  method: grant_permission
  classification:
    domain: workspace
    subdomain: casefile_acl
    capability: update
    complexity: atomic
    maturity: stable
    integration_tier: internal
method_params:
- name: request
  type: object
  required: true
  description: Request object
tool_params:
- name: timeout_seconds
  type: integer
  required: false
  description: Maximum execution time in seconds
  default: 30
  min_value: 5
  max_value: 300
- name: dry_run
  type: boolean
  required: false
  description: Preview mode without actual execution
  default: false
implementation:
  type: method_wrapper
  method_wrapper:
    method_name: CasefileService.grant_permission
    parameter_mapping:
      method_params:
      - request
      tool_params:
      - timeout_seconds
      - dry_run
business_rules:
  enabled: true
  requires_auth: true
  required_permissions:
  - casefiles:share
  requires_casefile: true
  casefile_permission_level: admin
  timeout_seconds: 30
examples:
- description: Basic grant_permission operation
  input:
    request: sample_request
  expected_output:
    result: success
    data: {}
data_contracts:
  request_model: GrantPermissionRequest
  response_model: GrantPermissionResponse
  canonical_models: []
  module: src.pydantic_models.operations.casefile_ops
dependencies:
  methods:
  - grant_permission
  models:
  - GrantPermissionRequest
  - GrantPermissionResponse
  services:
  - CasefileService
compatibility:
  method_version: 1.0.0
  schema_version: '1.0'
  requires_auth: true
