name: delete_casefile_tool
description: Tool wrapper for CasefileService.delete_casefile with validation and
  execution control
category: workspace_management
version: 1.0.0
tags:
- workspace
- delete
- delete
method_reference:
  service: CasefileService
  method: delete_casefile
  classification:
    domain: workspace
    subdomain: casefile
    capability: delete
    complexity: atomic
    maturity: stable
    integration_tier: internal
method_params:
- name: request
  type: object
  required: true
  description: Request object
tool_params:
- name: timeout_seconds
  type: integer
  required: false
  description: Maximum execution time in seconds
  default: 30
  min_value: 5
  max_value: 300
- name: dry_run
  type: boolean
  required: false
  description: Preview mode without actual execution
  default: false
implementation:
  type: method_wrapper
  method_wrapper:
    method_name: CasefileService.delete_casefile
    parameter_mapping:
      method_params:
      - request
      tool_params:
      - timeout_seconds
      - dry_run
business_rules:
  enabled: true
  requires_auth: true
  required_permissions:
  - casefiles:delete
  requires_casefile: true
  casefile_permission_level: owner
  timeout_seconds: 30
examples:
- description: Basic delete_casefile operation
  input:
    request: sample_request
  expected_output:
    result: success
    data: {}
data_contracts:
  request_model: DeleteCasefileRequest
  response_model: DeleteCasefileResponse
  canonical_models: []
  module: src.pydantic_models.operations.casefile_ops
dependencies:
  methods:
  - delete_casefile
  models:
  - DeleteCasefileRequest
  - DeleteCasefileResponse
  services:
  - CasefileService
compatibility:
  method_version: 1.0.0
  schema_version: '1.0'
  requires_auth: true
