name: store_sheet_data_tool
description: Tool wrapper for CasefileService.store_sheet_data with validation and
  execution control
category: workspace_management
version: 1.0.0
tags:
- workspace
- update
- store
method_reference:
  service: CasefileService
  method: store_sheet_data
  classification:
    domain: workspace
    subdomain: google_workspace
    capability: update
    complexity: composite
    maturity: beta
    integration_tier: hybrid
method_params:
- name: request
  type: object
  required: true
  description: Request object
tool_params:
- name: timeout_seconds
  type: integer
  required: false
  description: Maximum execution time in seconds
  default: 60
  min_value: 5
  max_value: 300
- name: dry_run
  type: boolean
  required: false
  description: Preview mode without actual execution
  default: false
implementation:
  type: method_wrapper
  method_wrapper:
    method_name: CasefileService.store_sheet_data
    parameter_mapping:
      method_params:
      - request
      tool_params:
      - timeout_seconds
      - dry_run
business_rules:
  enabled: true
  requires_auth: true
  required_permissions:
  - casefiles:write
  - workspace:sheets:read
  requires_casefile: true
  casefile_permission_level: write
  timeout_seconds: 60
examples:
- description: Basic store_sheet_data operation
  input:
    request: sample_request
  expected_output:
    result: success
    data: {}
data_contracts:
  request_model: StoreSheetDataRequest
  response_model: StoreSheetDataResponse
  canonical_models: []
  module: src.pydantic_models.operations.casefile_ops
dependencies:
  methods:
  - store_sheet_data
  models:
  - StoreSheetDataRequest
  - StoreSheetDataResponse
  services:
  - CasefileService
compatibility:
  method_version: 1.0.0
  schema_version: '1.0'
  requires_auth: true
