name: add_session_to_casefile_tool
description: Tool wrapper for CasefileService.add_session_to_casefile with validation and execution control
category: workspace_management
version: 1.0.0
tags:
- workspace
- casefile
- update
method_reference:
  service: CasefileService
  method: add_session_to_casefile
  classification:
    domain: workspace
    subdomain: casefile
    capability: update
    complexity: atomic
    maturity: stable
    integration_tier: internal
method_params:
- name: casefile_id
  type: string
  required: true
  description: Casefile ID
- name: session_id
  type: string
  required: true
  description: Session ID to add (ts_* or cs_*)
- name: session_type
  type: string
  required: true
  description: Type of session
tool_params:
- name: casefile_id
  type: string
  required: true
  description: Casefile ID
- name: session_id
  type: string
  required: true
  description: Session ID to add (ts_* or cs_*)
- name: session_type
  type: string
  required: true
  description: Type of session
- name: timeout_seconds
  type: integer
  required: false
  description: Maximum execution time in seconds
  default: 30
  min_value: 5
  max_value: 300
- name: dry_run
  type: boolean
  required: false
  description: Preview mode without actual execution
  default: false
implementation:
  type: method_wrapper
  method_wrapper:
    method_name: CasefileService.add_session_to_casefile
    parameter_mapping:
      method_params:
      - casefile_id
      - session_id
      - session_type
      tool_params:
      - timeout_seconds
      - dry_run
business_rules:
  enabled: true
  requires_auth: true
  required_permissions:
  - casefiles:write
  requires_casefile: true
  timeout_seconds: 30
examples:
- description: Basic add_session_to_casefile operation
  input:
    casefile_id: sample_casefile_id
    session_id: sample_session_id
  expected_output:
    result: success
    data: {}
data_contracts:
  request_model: AddSessionToCasefileRequest
  response_model: AddSessionToCasefileResponse
  canonical_models: []
  module: src.pydantic_models.operations.casefile_ops
dependencies:
  methods:
  - add_session_to_casefile
  models:
  - AddSessionToCasefileRequest
  - AddSessionToCasefileResponse
  services:
  - CasefileService
compatibility:
  method_version: 1.0.0
  schema_version: '1.0'
  requires_auth: true
