name: store_drive_files_tool
description: Tool wrapper for casefile.store_drive_files with validation and execution control
category: workspace_management
version: 1.0.0
tags:
- workspace
- google_workspace
- update
method_reference:
  service: casefile
  method: store_drive_files
  classification:
    domain: workspace
    subdomain: google_workspace
    capability: update
    complexity: composite
    maturity: beta
    integration_tier: hybrid
method_params:
- name: casefile_id
  type: string
  required: true
  description: Casefile ID
- name: files
  type: array
  required: true
  description: Drive files (DriveFile dicts)
- name: sync_token
  type: string
  required: false
  description: Incremental sync token from Drive API
- name: overwrite
  type: boolean
  required: false
  description: Replace existing cache instead of merging
  default: false
tool_params:
- name: casefile_id
  type: string
  required: true
  description: Casefile ID
- name: files
  type: array
  required: true
  description: Drive files (DriveFile dicts)
- name: sync_token
  type: string
  required: false
  description: Incremental sync token from Drive API
- name: overwrite
  type: boolean
  required: false
  description: Replace existing cache instead of merging
  default: false
- name: timeout_seconds
  type: integer
  required: false
  description: Maximum execution time in seconds
  default: 30
  min_value: 5
  max_value: 300
- name: dry_run
  type: boolean
  required: false
  description: Preview mode without actual execution
  default: false
implementation:
  type: method_wrapper
  method_wrapper:
    method_name: casefile.store_drive_files
    parameter_mapping:
      method_params:
      - casefile_id
      - files
      - sync_token
      - overwrite
      tool_params:
      - timeout_seconds
      - dry_run
business_rules:
  enabled: true
  requires_auth: true
  required_permissions: []
  requires_casefile: false
  timeout_seconds: 30
examples:
- description: Basic store_drive_files operation
  input:
    casefile_id: sample_casefile_id
    files: sample_files
  expected_output:
    result: success
    data: {}
data_contracts:
  request_model: StoreDriveFilesRequest
  response_model: StoreDriveFilesResponse
  canonical_models: []
  module: pydantic_models.operations.casefile_ops
dependencies:
  methods:
  - store_drive_files
  models:
  - StoreDriveFilesRequest
  - StoreDriveFilesResponse
  services:
  - casefile
compatibility:
  method_version: 1.0.0
  schema_version: '1.0'
  requires_auth: true
