name: check_permission_tool
description: Tool wrapper for CasefileService.check_permission with validation and execution control
category: workspace_management
version: 1.0.0
tags:
- workspace
- casefile_acl
- read
method_reference:
  service: CasefileService
  method: check_permission
  classification:
    domain: workspace
    subdomain: casefile_acl
    capability: read
    complexity: atomic
    maturity: stable
    integration_tier: internal
method_params:
- name: casefile_id
  type: string
  required: true
  description: Casefile ID
- name: user_id
  type: string
  required: true
  description: User ID to check
- name: required_permission
  type: string
  required: true
  description: Required permission level
tool_params:
- name: casefile_id
  type: string
  required: true
  description: Casefile ID
- name: user_id
  type: string
  required: true
  description: User ID to check
- name: required_permission
  type: string
  required: true
  description: Required permission level
- name: timeout_seconds
  type: integer
  required: false
  description: Maximum execution time in seconds
  default: 30
  min_value: 5
  max_value: 300
- name: dry_run
  type: boolean
  required: false
  description: Preview mode without actual execution
  default: false
implementation:
  type: method_wrapper
  method_wrapper:
    method_name: CasefileService.check_permission
    parameter_mapping:
      method_params:
      - casefile_id
      - user_id
      - required_permission
      tool_params:
      - timeout_seconds
      - dry_run
business_rules:
  enabled: true
  requires_auth: true
  required_permissions:
  - casefiles:read
  requires_casefile: true
  timeout_seconds: 30
examples:
- description: Basic check_permission operation
  input:
    casefile_id: sample_casefile_id
    user_id: sample_user_id
  expected_output:
    result: success
    data: {}
data_contracts:
  request_model: CheckPermissionRequest
  response_model: CheckPermissionResponse
  canonical_models: []
  module: src.pydantic_models.operations.casefile_ops
dependencies:
  methods:
  - check_permission
  models:
  - CheckPermissionRequest
  - CheckPermissionResponse
  services:
  - CasefileService
compatibility:
  method_version: 1.0.0
  schema_version: '1.0'
  requires_auth: true
