name: store_sheet_data_tool
description: Tool wrapper for casefile.store_sheet_data with validation and execution control
category: workspace_management
version: 1.0.0
tags:
- workspace
- google_workspace
- update
method_reference:
  service: casefile
  method: store_sheet_data
  classification:
    domain: workspace
    subdomain: google_workspace
    capability: update
    complexity: composite
    maturity: beta
    integration_tier: hybrid
method_params:
- name: casefile_id
  type: string
  required: true
  description: Casefile ID
- name: sheet_payloads
  type: array
  required: true
  description: Sheet data (SheetData dicts)
- name: sync_token
  type: string
  required: false
  description: Incremental sync token from Sheets API
tool_params:
- name: casefile_id
  type: string
  required: true
  description: Casefile ID
- name: sheet_payloads
  type: array
  required: true
  description: Sheet data (SheetData dicts)
- name: sync_token
  type: string
  required: false
  description: Incremental sync token from Sheets API
- name: timeout_seconds
  type: integer
  required: false
  description: Maximum execution time in seconds
  default: 30
  min_value: 5
  max_value: 300
- name: dry_run
  type: boolean
  required: false
  description: Preview mode without actual execution
  default: false
implementation:
  type: method_wrapper
  method_wrapper:
    method_name: casefile.store_sheet_data
    parameter_mapping:
      method_params:
      - casefile_id
      - sheet_payloads
      - sync_token
      tool_params:
      - timeout_seconds
      - dry_run
business_rules:
  enabled: true
  requires_auth: true
  required_permissions: []
  requires_casefile: false
  timeout_seconds: 30
examples:
- description: Basic store_sheet_data operation
  input:
    casefile_id: sample_casefile_id
    sheet_payloads: sample_sheet_payloads
  expected_output:
    result: success
    data: {}
data_contracts:
  request_model: StoreSheetDataRequest
  response_model: StoreSheetDataResponse
  canonical_models: []
  module: pydantic_models.operations.casefile_ops
dependencies:
  methods:
  - store_sheet_data
  models:
  - StoreSheetDataRequest
  - StoreSheetDataResponse
  services:
  - casefile
compatibility:
  method_version: 1.0.0
  schema_version: '1.0'
  requires_auth: true
