name: list_files_tool
description: Tool wrapper for DriveClient.list_files with validation and execution control
category: workspace_management
version: 1.0.0
tags:
- workspace
- google_drive
- read
method_reference:
  service: DriveClient
  method: list_files
  classification:
    domain: workspace
    subdomain: google_drive
    capability: read
    complexity: atomic
    maturity: beta
    integration_tier: external
method_params: []
tool_params:
- name: timeout_seconds
  type: integer
  required: false
  description: Maximum execution time in seconds
  default: 30
  min_value: 5
  max_value: 300
- name: dry_run
  type: boolean
  required: false
  description: Preview mode without actual execution
  default: false
implementation:
  type: method_wrapper
  method_wrapper:
    method_name: DriveClient.list_files
    parameter_mapping:
      method_params: []
      tool_params:
      - timeout_seconds
      - dry_run
business_rules:
  enabled: true
  requires_auth: true
  required_permissions:
  - workspace:drive:read
  requires_casefile: false
  timeout_seconds: 30
examples:
- description: Basic list_files operation
  input: {}
  expected_output:
    result: success
    data: {}
data_contracts:
  request_model: DriveListFilesRequest
  response_model: DriveListFilesResponse
  canonical_models: []
  module: src.pydantic_ai_integration.integrations.google_workspace.models
dependencies:
  methods:
  - list_files
  models:
  - DriveListFilesRequest
  - DriveListFilesResponse
  services:
  - DriveClient
compatibility:
  method_version: 1.0.0
  schema_version: '1.0'
  requires_auth: true
