name: execute_casefile_with_session_tool
description: Tool wrapper for RequestHubService.execute_casefile_with_session with validation and execution control
category: workspace_management
version: 1.0.0
tags:
- workspace
- casefile
- create
method_reference:
  service: RequestHubService
  method: execute_casefile_with_session
  classification:
    domain: workspace
    subdomain: casefile
    capability: create
    complexity: composite
    maturity: beta
    integration_tier: internal
method_params:
- name: title
  type: string
  required: true
  description: Casefile title
  min_length: 1
  max_length: 200
- name: description
  type: string
  required: false
  description: Casefile description
  max_length: 2000
- name: tags
  type: array
  required: false
  description: Tags for categorization
- name: auto_start_session
  type: boolean
  required: false
  description: Whether a tool session should be created
  default: true
- name: session_title
  type: string
  required: false
  description: Optional explicit session title
- name: hook_channels
  type: array
  required: false
  description: Optional hook identifiers to activate for this workflow.
tool_params:
- name: title
  type: string
  required: true
  description: Casefile title
  min_length: 1
  max_length: 200
- name: description
  type: string
  required: false
  description: Casefile description
  max_length: 2000
- name: tags
  type: array
  required: false
  description: Tags for categorization
- name: auto_start_session
  type: boolean
  required: false
  description: Whether a tool session should be created
  default: true
- name: session_title
  type: string
  required: false
  description: Optional explicit session title
- name: hook_channels
  type: array
  required: false
  description: Optional hook identifiers to activate for this workflow.
- name: timeout_seconds
  type: integer
  required: false
  description: Maximum execution time in seconds
  default: 30
  min_value: 5
  max_value: 300
- name: dry_run
  type: boolean
  required: false
  description: Preview mode without actual execution
  default: false
implementation:
  type: method_wrapper
  method_wrapper:
    method_name: RequestHubService.execute_casefile_with_session
    parameter_mapping:
      method_params:
      - title
      - description
      - tags
      - auto_start_session
      - session_title
      - hook_channels
      tool_params:
      - timeout_seconds
      - dry_run
business_rules:
  enabled: true
  requires_auth: true
  required_permissions:
  - casefiles:write
  - tool_sessions:write
  requires_casefile: false
  timeout_seconds: 60
examples:
- description: Basic execute_casefile_with_session operation
  input:
    title: sample_title
    description: sample_description
  expected_output:
    result: success
    data: {}
data_contracts:
  request_model: CreateCasefileWithSessionRequest
  response_model: CreateCasefileWithSessionResponse
  canonical_models: []
  module: src.pydantic_models.operations.request_hub_ops
dependencies:
  methods:
  - execute_casefile_with_session
  models:
  - CreateCasefileWithSessionRequest
  - CreateCasefileWithSessionResponse
  services:
  - RequestHubService
compatibility:
  method_version: 1.0.0
  schema_version: '1.0'
  requires_auth: true
