name: execute_casefile_with_session_tool
description: Tool wrapper for RequestHubService.execute_casefile_with_session with
  validation and execution control
category: workspace_management
version: 1.0.0
tags:
- workspace
- create
- execute
method_reference:
  service: RequestHubService
  method: execute_casefile_with_session
  classification:
    domain: workspace
    subdomain: casefile
    capability: create
    complexity: composite
    maturity: beta
    integration_tier: internal
method_params:
- name: request
  type: object
  required: true
  description: Request object
tool_params:
- name: timeout_seconds
  type: integer
  required: false
  description: Maximum execution time in seconds
  default: 60
  min_value: 5
  max_value: 300
- name: dry_run
  type: boolean
  required: false
  description: Preview mode without actual execution
  default: false
implementation:
  type: method_wrapper
  method_wrapper:
    method_name: RequestHubService.execute_casefile_with_session
    parameter_mapping:
      method_params:
      - request
      tool_params:
      - timeout_seconds
      - dry_run
business_rules:
  enabled: true
  requires_auth: true
  required_permissions:
  - casefiles:write
  - tool_sessions:write
  requires_casefile: false
  timeout_seconds: 60
examples:
- description: Basic execute_casefile_with_session operation
  input:
    request: sample_request
  expected_output:
    result: success
    data: {}
data_contracts:
  request_model: CreateCasefileWithSessionRequest
  response_model: CreateCasefileWithSessionResponse
  canonical_models: []
  module: src.pydantic_models.operations.request_hub_ops
dependencies:
  methods:
  - execute_casefile_with_session
  models:
  - CreateCasefileWithSessionRequest
  - CreateCasefileWithSessionResponse
  services:
  - RequestHubService
compatibility:
  method_version: 1.0.0
  schema_version: '1.0'
  requires_auth: true
