name: create_session_with_casefile_tool
description: Tool wrapper for RequestHubService.create_session_with_casefile with
  validation and execution control
category: automation_management
version: 1.0.0
tags:
- automation
- create
- create
method_reference:
  service: RequestHubService
  method: create_session_with_casefile
  classification:
    domain: automation
    subdomain: tool_session
    capability: create
    complexity: composite
    maturity: beta
    integration_tier: internal
method_params:
- name: request
  type: object
  required: true
  description: Request object
tool_params:
- name: timeout_seconds
  type: integer
  required: false
  description: Maximum execution time in seconds
  default: 60
  min_value: 5
  max_value: 300
- name: dry_run
  type: boolean
  required: false
  description: Preview mode without actual execution
  default: false
implementation:
  type: method_wrapper
  method_wrapper:
    method_name: RequestHubService.create_session_with_casefile
    parameter_mapping:
      method_params:
      - request
      tool_params:
      - timeout_seconds
      - dry_run
business_rules:
  enabled: true
  requires_auth: true
  required_permissions:
  - tools:execute
  - casefiles:write
  requires_casefile: true
  casefile_permission_level: write
  timeout_seconds: 60
examples:
- description: Basic create_session_with_casefile operation
  input:
    request: sample_request
  expected_output:
    result: success
    data: {}
data_contracts:
  request_model: CreateSessionWithCasefileRequest
  response_model: CreateSessionWithCasefileResponse
  canonical_models: []
  module: src.pydantic_models.operations.request_hub_ops
dependencies:
  methods:
  - create_session_with_casefile
  models:
  - CreateSessionWithCasefileRequest
  - CreateSessionWithCasefileResponse
  services:
  - RequestHubService
compatibility:
  method_version: 1.0.0
  schema_version: '1.0'
  requires_auth: true
