name: create_session_with_casefile_tool
description: Tool wrapper for RequestHubService.create_session_with_casefile with validation and execution control
category: automation
version: 1.0.0
tags:
- automation
- tool_session
- create
method_reference:
  service: RequestHubService
  method: create_session_with_casefile
  classification:
    domain: automation
    subdomain: tool_session
    capability: create
    complexity: composite
    maturity: beta
    integration_tier: internal
method_params:
- name: casefile_id
  type: string
  required: true
  description: Existing casefile ID to link session to
- name: title
  type: string
  required: false
  description: Optional session title
- name: session_type
  type: string
  required: false
  description: Type of session to create (tool or chat)
  default: tool
tool_params:
- name: casefile_id
  type: string
  required: true
  description: Existing casefile ID to link session to
- name: title
  type: string
  required: false
  description: Optional session title
- name: session_type
  type: string
  required: false
  description: Type of session to create (tool or chat)
  default: tool
- name: timeout_seconds
  type: integer
  required: false
  description: Maximum execution time in seconds
  default: 30
  min_value: 5
  max_value: 300
- name: dry_run
  type: boolean
  required: false
  description: Preview mode without actual execution
  default: false
implementation:
  type: method_wrapper
  method_wrapper:
    method_name: RequestHubService.create_session_with_casefile
    parameter_mapping:
      method_params:
      - casefile_id
      - title
      - session_type
      tool_params:
      - timeout_seconds
      - dry_run
business_rules:
  enabled: true
  requires_auth: true
  required_permissions:
  - tools:execute
  - casefiles:write
  requires_casefile: true
  timeout_seconds: 60
examples:
- description: Basic create_session_with_casefile operation
  input:
    casefile_id: sample_casefile_id
    title: sample_title
  expected_output:
    result: success
    data: {}
data_contracts:
  request_model: CreateSessionWithCasefileRequest
  response_model: CreateSessionWithCasefileResponse
  canonical_models: []
  module: src.pydantic_models.operations.request_hub_ops
dependencies:
  methods:
  - create_session_with_casefile
  models:
  - CreateSessionWithCasefileRequest
  - CreateSessionWithCasefileResponse
  services:
  - RequestHubService
compatibility:
  method_version: 1.0.0
  schema_version: '1.0'
  requires_auth: true
