name: process_tool_request_tool
description: Tool wrapper for ToolSessionService.process_tool_request with validation and execution control
category: automation
version: 1.0.0
tags:
- automation
- tool_execution
- process
method_reference:
  service: ToolSessionService
  method: process_tool_request
  classification:
    domain: automation
    subdomain: tool_execution
    capability: process
    complexity: pipeline
    maturity: stable
    integration_tier: hybrid
method_params:
- name: tool_name
  type: string
  required: true
  description: Name of the tool to execute
  min_length: 1
  max_length: 200
- name: parameters
  type: object
  required: false
  description: Parameters for the tool
- name: prompt
  type: string
  required: false
  description: Optional prompt for AI-assisted tool execution
- name: casefile_id
  type: string
  required: false
  description: Optional casefile context
- name: session_request_id
  type: string
  required: false
  description: Client-provided session request ID for tracking
tool_params:
- name: tool_name
  type: string
  required: true
  description: Name of the tool to execute
  min_length: 1
  max_length: 200
- name: parameters
  type: object
  required: false
  description: Parameters for the tool
- name: prompt
  type: string
  required: false
  description: Optional prompt for AI-assisted tool execution
- name: casefile_id
  type: string
  required: false
  description: Optional casefile context
- name: session_request_id
  type: string
  required: false
  description: Client-provided session request ID for tracking
- name: timeout_seconds
  type: integer
  required: false
  description: Maximum execution time in seconds
  default: 30
  min_value: 5
  max_value: 300
- name: dry_run
  type: boolean
  required: false
  description: Preview mode without actual execution
  default: false
implementation:
  type: method_wrapper
  method_wrapper:
    method_name: ToolSessionService.process_tool_request
    parameter_mapping:
      method_params:
      - tool_name
      - parameters
      - prompt
      - casefile_id
      - session_request_id
      tool_params:
      - timeout_seconds
      - dry_run
business_rules:
  enabled: true
  requires_auth: true
  required_permissions:
  - tools:execute
  requires_casefile: false
  timeout_seconds: 60
examples:
- description: Basic process_tool_request operation
  input:
    tool_name: sample_tool_name
    parameters: sample_parameters
  expected_output:
    result: success
    data: {}
data_contracts:
  request_model: ToolRequest
  response_model: ToolResponse
  canonical_models: []
  module: src.pydantic_models.operations.tool_execution_ops
dependencies:
  methods:
  - process_tool_request
  models:
  - ToolRequest
  - ToolResponse
  services:
  - ToolSessionService
compatibility:
  method_version: 1.0.0
  schema_version: '1.0'
  requires_auth: true
