name: process_tool_request_tool
description: Tool wrapper for ToolSessionService.process_tool_request with validation
  and execution control
category: automation_management
version: 1.0.0
tags:
- automation
- process
- process
method_reference:
  service: ToolSessionService
  method: process_tool_request
  classification:
    domain: automation
    subdomain: tool_execution
    capability: process
    complexity: pipeline
    maturity: stable
    integration_tier: hybrid
method_params:
- name: request
  type: object
  required: true
  description: Request object
tool_params:
- name: timeout_seconds
  type: integer
  required: false
  description: Maximum execution time in seconds
  default: 60
  min_value: 5
  max_value: 300
- name: dry_run
  type: boolean
  required: false
  description: Preview mode without actual execution
  default: false
implementation:
  type: method_wrapper
  method_wrapper:
    method_name: ToolSessionService.process_tool_request
    parameter_mapping:
      method_params:
      - request
      tool_params:
      - timeout_seconds
      - dry_run
business_rules:
  enabled: true
  requires_auth: true
  required_permissions:
  - tools:execute
  requires_casefile: false
  timeout_seconds: 60
examples:
- description: Basic process_tool_request operation
  input:
    request: sample_request
  expected_output:
    result: success
    data: {}
data_contracts:
  request_model: ToolRequest
  response_model: ToolResponse
  canonical_models: []
  module: src.pydantic_models.operations.tool_execution_ops
dependencies:
  methods:
  - process_tool_request
  models:
  - ToolRequest
  - ToolResponse
  services:
  - ToolSessionService
compatibility:
  method_version: 1.0.0
  schema_version: '1.0'
  requires_auth: true
