name: list_sessions_tool
description: Tool wrapper for ToolSessionService.list_sessions with validation and execution control
category: automation
version: 1.0.0
tags:
- automation
- tool_session
- search
method_reference:
  service: ToolSessionService
  method: list_sessions
  classification:
    domain: automation
    subdomain: tool_session
    capability: search
    complexity: atomic
    maturity: stable
    integration_tier: internal
method_params:
- name: user_id
  type: string
  required: false
  description: Filter by user ID
- name: casefile_id
  type: string
  required: false
  description: Filter by casefile ID
- name: active_only
  type: boolean
  required: false
  description: Only return active sessions
  default: true
- name: limit
  type: integer
  required: false
  description: Maximum results to return
  min_value: 1
  max_value: 100
  default: 50
- name: offset
  type: integer
  required: false
  description: Offset for pagination
  min_value: 0
  default: 0
tool_params:
- name: user_id
  type: string
  required: false
  description: Filter by user ID
- name: casefile_id
  type: string
  required: false
  description: Filter by casefile ID
- name: active_only
  type: boolean
  required: false
  description: Only return active sessions
  default: true
- name: limit
  type: integer
  required: false
  description: Maximum results to return
  min_value: 1
  max_value: 100
  default: 50
- name: offset
  type: integer
  required: false
  description: Offset for pagination
  min_value: 0
  default: 0
- name: timeout_seconds
  type: integer
  required: false
  description: Maximum execution time in seconds
  default: 30
  min_value: 5
  max_value: 300
- name: dry_run
  type: boolean
  required: false
  description: Preview mode without actual execution
  default: false
implementation:
  type: method_wrapper
  method_wrapper:
    method_name: ToolSessionService.list_sessions
    parameter_mapping:
      method_params:
      - user_id
      - casefile_id
      - active_only
      - limit
      - offset
      tool_params:
      - timeout_seconds
      - dry_run
business_rules:
  enabled: true
  requires_auth: true
  required_permissions:
  - tools:read
  requires_casefile: false
  timeout_seconds: 30
examples:
- description: Basic list_sessions operation
  input:
    user_id: sample_user_id
    casefile_id: sample_casefile_id
  expected_output:
    result: success
    data: {}
data_contracts:
  request_model: ListSessionsRequest
  response_model: ListSessionsResponse
  canonical_models: []
  module: src.pydantic_models.operations.tool_session_ops
dependencies:
  methods:
  - list_sessions
  models:
  - ListSessionsRequest
  - ListSessionsResponse
  services:
  - ToolSessionService
compatibility:
  method_version: 1.0.0
  schema_version: '1.0'
  requires_auth: true
