name: close_session_tool
description: Tool wrapper for ToolSessionService.close_session with validation and
  execution control
category: automation_management
version: 1.0.0
tags:
- automation
- update
- close
method_reference:
  service: ToolSessionService
  method: close_session
  classification:
    domain: automation
    subdomain: tool_session
    capability: update
    complexity: atomic
    maturity: stable
    integration_tier: internal
method_params:
- name: request
  type: object
  required: true
  description: Request object
tool_params:
- name: timeout_seconds
  type: integer
  required: false
  description: Maximum execution time in seconds
  default: 30
  min_value: 5
  max_value: 300
- name: dry_run
  type: boolean
  required: false
  description: Preview mode without actual execution
  default: false
implementation:
  type: method_wrapper
  method_wrapper:
    method_name: ToolSessionService.close_session
    parameter_mapping:
      method_params:
      - request
      tool_params:
      - timeout_seconds
      - dry_run
business_rules:
  enabled: true
  requires_auth: true
  required_permissions:
  - tools:execute
  requires_casefile: false
  timeout_seconds: 30
examples:
- description: Basic close_session operation
  input:
    request: sample_request
  expected_output:
    result: success
    data: {}
data_contracts:
  request_model: CloseSessionRequest
  response_model: CloseSessionResponse
  canonical_models: []
  module: src.pydantic_models.operations.tool_session_ops
dependencies:
  methods:
  - close_session
  models:
  - CloseSessionRequest
  - CloseSessionResponse
  services:
  - ToolSessionService
compatibility:
  method_version: 1.0.0
  schema_version: '1.0'
  requires_auth: true
