name: create_session_tool
description: Tool wrapper for ToolSessionService.create_session with validation and execution control
category: automation
version: 1.0.0
tags:
- automation
- tool_session
- create
method_reference:
  service: ToolSessionService
  method: create_session
  classification:
    domain: automation
    subdomain: tool_session
    capability: create
    complexity: atomic
    maturity: stable
    integration_tier: internal
method_params:
- name: casefile_id
  type: string
  required: false
  description: Optional casefile ID to associate with session
- name: title
  type: string
  required: false
  description: Optional session title
tool_params:
- name: casefile_id
  type: string
  required: false
  description: Optional casefile ID to associate with session
- name: title
  type: string
  required: false
  description: Optional session title
- name: timeout_seconds
  type: integer
  required: false
  description: Maximum execution time in seconds
  default: 30
  min_value: 5
  max_value: 300
- name: dry_run
  type: boolean
  required: false
  description: Preview mode without actual execution
  default: false
implementation:
  type: method_wrapper
  method_wrapper:
    method_name: ToolSessionService.create_session
    parameter_mapping:
      method_params:
      - casefile_id
      - title
      tool_params:
      - timeout_seconds
      - dry_run
business_rules:
  enabled: true
  requires_auth: true
  required_permissions:
  - tools:execute
  requires_casefile: false
  timeout_seconds: 30
examples:
- description: Basic create_session operation
  input:
    casefile_id: sample_casefile_id
    title: sample_title
  expected_output:
    result: success
    data: {}
data_contracts:
  request_model: CreateSessionRequest
  response_model: CreateSessionResponse
  canonical_models: []
  module: src.pydantic_models.operations.tool_session_ops
dependencies:
  methods:
  - create_session
  models:
  - CreateSessionRequest
  - CreateSessionResponse
  services:
  - ToolSessionService
compatibility:
  method_version: 1.0.0
  schema_version: '1.0'
  requires_auth: true
