name: MVP Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  validate:
    name: Validate and Test MVP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Baseline Tests (echo_tool)
        run: |
          python -m pytest tests/generated/test_echo_tool.py -v --tb=short

      - name: Validate Tool YAML Definitions
        run: |
          python -c "
          import yaml
          import sys
          from pathlib import Path
          
          errors = []
          for yaml_file in Path('config/tools').glob('*.yaml'):
              try:
                  with open(yaml_file) as f:
                      yaml.safe_load(f)
                  print(f'✓ {yaml_file.name}')
              except Exception as e:
                  errors.append(f'✗ {yaml_file.name}: {e}')
          
          if errors:
              print('\nErrors found:')
              for error in errors:
                  print(error)
              sys.exit(1)
          "
